### PR TITLE
Ensure new default branch main is used by Galaxy

### LINKED ISSUE #13: Rename default branch to `main`
Follow up from https://github.com/hifis-net/ansible-role-unattended-upgrades/pull/9#discussion_r947484750

### PR DESCRIPTION
**Pull request by Normo**
* Closes #13

### CODE REVIEW

**Review by tobiashuste — CHANGES_REQUESTED** [review]
`github_branch` is only valid for collection metadata as far as I know. Ansible-lint also complains.

We should probably update this line instead:

https://github.com/hifis-net/ansible-role-unattended-upgrades/blob/9032da93066376d4dbd56f9f7a11455b477eb2c5/.github/workflows/ci.yml#L74

**Comment by Normo** [comment]
@tobiashuste Strange, then the Galaxy [documentation](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata) seems to be inconsistent.

**Comment by tobiashuste** [comment]
> @tobiashuste Strange, then the Galaxy [documentation](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata) seems to be inconsistent.

You're right, @Normo!

It could be that `standalone: true` fixes the ansible-lint complaints. See https://ansible-lint.readthedocs.io/rules/schema/#schema-meta.

**Review by tobiashuste — APPROVED** [review]
Thanks, @Normo :+1:

Feel free to merge once the pipeline succeeded.

**Pull request merged**
