### PR TITLE
Add changelog

### LINKED ISSUE #33: Add changelog

### PR DESCRIPTION
**Pull request by Normo**
* Closes #33

### CODE REVIEW

**Review by tobiashuste — APPROVED** [review]
Looks good to me. :) Thanks, @Normo!

**Review by christianhueserhzdr — CHANGES_REQUESTED** [review]
Dear Norman @Normo, do we need a separate license header file CHANGELOG.md.license for file CHANGELOG.md or a license header in file CHANGELOG.md? All else is fine. Thanks for generating a CHANGELOG for this project.

**Comment by Normo** [comment]
Thanks, @christianhueserhzdr for the hint. This project does not use license headers yet.

**Review by christianhueserhzdr — APPROVED** [review]
Dear Norman @Normo, alright, thanks for the clarification. I'll approve this PR now.

**Pull request merged**
